title: Biometrico0
description: 'Modulo web, '
template:
  repo: biometrico0-template
  name: biometrico0
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
